'use client';

import { ChakraProvider } from '@chakra-ui/react';
import { I18nProvider } from '@ttoss/react-i18n';
import type { LoadLocaleData } from '@ttoss/react-i18n';

import { EmotionRegistry } from './emotion-registry';
import { system } from './theme';

/**
 * Async loader for compiled FormatJS message bundles.
 * Files under `i18n/compiled/` are generated by `pnpm run i18n` (ttoss-i18n).
 * The `prebuild` script ensures they exist before Next.js compilation.
 */
const loadLocaleData: LoadLocaleData = async (locale) => {
  switch (locale) {
    case 'pt-BR':
      return (
        await import(
          /* webpackChunkName: "i18n-pt-BR" */ '../../i18n/compiled/pt-BR.json'
        )
      ).default;
    default:
      return (
        await import(
          /* webpackChunkName: "i18n-en" */ '../../i18n/compiled/en.json'
        )
      ).default;
  }
};

export const Providers = ({
  children,
  locale,
}: {
  children: React.ReactNode;
  locale?: string;
}) => (
  <EmotionRegistry>
    <I18nProvider locale={locale} loadLocaleData={loadLocaleData}>
      <ChakraProvider value={system}>{children}</ChakraProvider>
    </I18nProvider>
  </EmotionRegistry>
);
