/** A single map data row joining a geometry ID to a computed value. */
export type MapDataRow = {
  geometryId: number;
  value: number;
};

/** Raw shape of the maps-data.json static snapshot generated by generate_maps_data.py. */
export type StaticMapsDataSource = {
  year: number;
  thresholds: Record<string, Partial<Record<string, number[]>>>;
  mapData: Record<string, Partial<Record<string, MapDataRow[]>>>;
};
