/** Raw district data from the maps-data.json static snapshot. */
export type DistrictData = {
  ano: number;
  cod_distr: number;
  nome: string;
  municipio: string;
  geometry_id: number;
  count_65_69: number;
  count_70_74: number;
  count_75plus: number;
  total: number;
};

/** Raw shape of the maps-data.json static snapshot generated by generate_maps_data.py. */
export type StaticMapsDataSource = {
  districts: DistrictData[];
};
